#!/bin/bash

# Lic Setup
export LM_LICENSE_FILE=27000@mimic.ece.jhu.edu

# Tools
INSTALL_DIR=/cadence/installs
export PATH=${INSTALL_DIR}/XCELIUMMAIN_24.03.005/tools.lnx86/bin:${PATH}
export PATH=${INSTALL_DIR}/DDI-ISR1_23.11.000/bin:${PATH}
